### ISSUE TITLE
Rate limit apparently sending wrong reset time?

### ISSUE THREAD

**Issue by SharpBit** [fourjr/scapi-issuetracker#16]
My wrapper raised this during tests:
```
raise RateLimitError(url, code, int(resp.headers.get('x-ratelimit-reset')) - time.time())
E  brawlstats.errors.RateLimitError: ('https://brawlapi.cf/api/player?tag=AAA', 429, -2.4370181560516357)
```
-2.4370181560516357 is the Reset Unix Time - Current Unix Time (should be a positive number).

Instead it's giving me a 429 error code response and telling me to wait -2.4 seconds before requesting again.

**Comment by SharpBit** [comment]
@fourjr

**Comment by zihadmahiuddin** [comment]
Is it still an issue? @SharpBit

**Comment by SharpBit** [comment]
If it is, idc cuz my wrapper is official API only now
